"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useEffect } from "react";

import "./globals.css";
import toast, { Toaster } from "react-hot-toast";
import { store } from "../store/store";
import { Provider, useDispatch } from "react-redux";
import { usePathname } from "next/navigation";
import { UseDispatch } from "react-redux";
import { setUserLogin } from "@/store/userSlice";
const inter = Inter({ subsets: ["latin"] });
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout(
  

  {
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const dispatch=useDispatch()

  const pathname = usePathname();
  // useEffect(() => {
  //   if (typeof window !== "undefined") {
  //     if (pathname !== "/") {
  //       if (!localStorage.getItem("token")) {
  //         window.location.href = "/";
  //       }
  //     }
  //     if (pathname === "/") {
  //       if (localStorage.getItem("token")) {
  //       // dispatch(setUserLogin(true));

  //         window.location.href = "/";
  //       }
  //     }
  //   }
  // }, []);
  return (
        <Provider store={store}>
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
          {children}
      </body>
    </html>
          </Provider>
  );
}
